### PR TITLE
Attempt to fix CI.

### PR DESCRIPTION
**Pull request by maltevesper**
Attempt to fix travis ci by installing rust.

I figured since you did not have the time, and since I like green ci lights I will give this a spin.
Unfortunatly I am not sure how to test this apart from shoving a bunch of commits your way, and seeing how travis reacts.

### CODE REVIEW

**Comment by maltevesper** [comment]
Turns out this was a quick fix. Just updating the ubuntu version does the trick :).

Technically the config file could be shortened, however I think that causes more issues if separate adjustments become necessary, so I would not propose that.
```
os: linux
language: python

dist: xenial

install: pip install tox pytest

script: tox

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
```

**Comment by maltevesper** [comment]
While working on this I came across this link which really helped me to see if my config parses before I push it: https://config.travis-ci.com/explore. Since I found it only in a comment on SO I figure I leave the link here for future reference.

**Comment by maltevesper** [comment]
Just figured I might as well squash this :)

**Comment by terrencepreilly** [comment]
Thanks for looking into this!

**Pull request merged**
